name: Bark Push

on:
  schedule:
    - cron: '40 23 * * *'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Send Bark
        run: |
          curl "https://api.day.app/DV43twTRNjcKqnqFAQvE7L/祁宴/该找我聊天了"
